# Consumer expenditure categorization

### Why relational learning matters

This example demonstrates how powerful a real relational learning algorithm can be. Based on a public-domain dataset on consumer behavior, we use a propostionalization algorithm to predict whether purchases were made as a gift. We show that with relational learning, we can get an AUC of over 90%. The generated features would have been impossible to build by hand or by using brute-force approaches.

Summary:

- Prediction type: __Classification model__
- Domain: __Retail__
- Prediction target: __If a purchase is a gift__ 
- Source data: __Relational data set, 4 tables__
- Population size: __398.895__

_Author: Patrick Urbanke_

# Background

Relational learning is one of the most underappreciated fields of machine learning. Even though relational learning is very relevant to many real world data science projects, many data scientists don't even know what relational learning is. 

There are many subdomains of relational learning, but the most important one is extracting features from relational data: Most business data is relational, meaning that it is spread out over several relational tables. However, most machine learning algorithms require that the data be presented in the form of a single flat table. So we need to extract features from our relational data. Some people also call this data wrangling.

Most data scientists we know extract features from relational data manually or by using crude, brute-force approaches (randomly generate thousands of features and then do a feature selection). This is very time-consuming and does not produce good features.

### The challenge

The Consumer Expenditure Data Set is a public domain data set provided by the American Bureau of Labor Statistics (https://www.bls.gov/cex/pumd.htm). It includes the diary entries, where American consumers are asked to keep diaries of the products they have purchased each month.

These consumer goods are categorized using a six-digit classification system the UCC. This system is hierarchical, meaning that every digit represents an increasingly granular category.

For instance, all UCC codes beginning with ‘200’ represent beverages. UCC codes beginning with ‘20011’ represents beer and ‘200111’ represents ‘beer and ale’ and ‘200112’ represents ‘nonalcoholic beer’ (https://www.bls.gov/cex/pumd/ce_pumd_interview_diary_dictionary.xlsx).

The diaries also contain a flag that indicates whether the product was purchased as a gift. The challenge is to predict that flag using other information in the diary entries.

This can be done based on the following considerations:

1. Some items are _less likely to be purchased as gifts_ than others (for instance, it is unlikely that toilet paper is ever purchased as a gift).

2. Items that diverge from the _usual consumption patterns_ are more likely to be gifts.

In total, there are three tables which we find interesting:

1. EXPD, which contains information on the _consumer expenditures_, including the target variable GIFT.

2. FMLD, which contains socio-demographic information on the _households_.

3. MEMD, which contains socio-demographic information on each _member of the households_.

### A web frontend for getML

The getML monitor is a frontend built to support your work with getML. The getML monitor displays information such as the imported data frames, trained pipelines and allows easy data and feature exploration. You can launch the getML monitor [here](http://localhost:1709).

### Where is this running?

Your getML live session is running inside a docker container on [mybinder.org](https://mybinder.org/), a service built by the Jupyter community and funded by Google Cloud, OVH, GESIS Notebooks and the Turing Institute. As it is a free service, this session will shut down after 10 minutes of inactivity.

# Analysis

In [1]:
import datetime
import os
from urllib import request
import time
import zipfile

import matplotlib.pyplot as plt
%matplotlib inline

import getml
from getml import data 
from getml import engine 
from getml import feature_learning 
from getml import hyperopt
from getml.feature_learning import loss_functions
from getml.pipeline import Pipeline
from getml.data import placeholder
from getml.data import roles 
from getml.pipeline import scores
from getml import predictors
from getml import preprocessors

## 1. Loading data

### 1.1 Download from source

First, we need to download and unzip the data. For your convenience, we have scripted this.

If you want to download them manually, you can use this link: https://www.bls.gov/cex/pumd.htm.

We will use the diary CSV files for the year 2015. There are more years you can use, but we will limit ourselves to this one year for now.

In [2]:
fname = "diary15.zip"

if not os.path.exists(fname):
    fname, res = request.urlretrieve(
        "https://www.bls.gov/cex/pumd/data/comma/diary15.zip", 
        "diary15.zip"
    )

RAW_DATA_FOLDER = "diary15/"

if not os.path.exists(RAW_DATA_FOLDER):
    with zipfile.ZipFile(fname, 'r') as dzip: 
        dzip.extractall()

We now set the project.

In getML, every data frame and model is tied to a project. If you change the project, then the memory is flushed and all unsaved changes are lost (but don't worry, models are saved automatically).

In [3]:
engine.set_project("consumer_expenditures")

Connected to project 'consumer_expenditures'

### 1.2 Prepare data for getML

We load the data directly into getML data frames. There are other ways to do this, such as using pandas or loading the data into a data base first. But we will us this approach.

In [4]:
# -----------------------------------------------------------------------------
# Load EXPD

expd_fnames = [
    RAW_DATA_FOLDER + "expd151.csv",
    RAW_DATA_FOLDER + "expd152.csv",
    RAW_DATA_FOLDER + "expd153.csv",
    RAW_DATA_FOLDER + "expd154.csv"
]

# The sniffer will interpret NEWID and UCC
# as a numeric column. But we want it
# to be treated as a string.
expd_roles = {"unused_string": ["UCC", "NEWID"]}

df_expd = data.DataFrame.from_csv(
    fnames=expd_fnames,
    name="EXPD",
    roles=expd_roles
)

df_expd

  Name          ALLOC           COST           GIFT       PUB_FLAG   ...   EXPNMO_         EXPNYR          EXPNYR_
  Role   unused_float   unused_float   unused_float   unused_float   ...   unused_string   unused_string   unused_string
     0              0         3.89                2              2   ...   D               2015            D
     1              1         4.3773              2              2   ...   D               2015            D
     2              1         3.5827              2              2   ...   D               2015            D
     3              0         5.58                2              2   ...   D               2015            D
     4              0         1.99                2              2   ...   D               2015            D
                  ...        ...                ...            ...         ...             ...             ...
412623              0         4.99                2              2   ...   D               2015            D
412624              1        11.6549              2              1   ...   D               2015            D
412625              1         7.99                2              2   ...   D               2015            D
412626              1         8.3351              2              2   ...   D               2015            D
412627              0       729                   2              1   ...   D               2015            D

  Name   UCC             NEWID
  Role   unused_string   unused_string
     0   010210          03111041
     1   060110          03111041
     2   060210          03111041
     3   090110          03111041
     4   090210          03111041
         ...             ...
412623   550210          03324162
412624   590230          03324162
412625   660000          03324162
412626   660000          03324162
412627   680110          03324162


412628 rows x 14 columns
memory usage: 60.96 MB
name: EXPD
type: getml.data.DataFrame
url: http://localhost:1709/#/getdataframe/consumer_expenditures/EXPD/

In [5]:
# -----------------------------------------------------------------------------
# Load FMLD

fmld_fnames = [
    RAW_DATA_FOLDER + "fmld151.csv",
    RAW_DATA_FOLDER + "fmld152.csv",
    RAW_DATA_FOLDER + "fmld153.csv",
    RAW_DATA_FOLDER + "fmld154.csv"
]

# The sniffer will interpret NEWID
# as a numeric column. But we want it
# to be treated as a string.
fmld_roles = {"unused_string": ["NEWID"]}

df_fmld = data.DataFrame.from_csv(
    fnames=fmld_fnames,
    name="FMLD",
    roles=fmld_roles
)

df_fmld

 Name       INC_RNKM       INC_RNK5       INC_RNK4       INC_RNK3   ...   INT__OME        INT__HON        DIVISION
 Role   unused_float   unused_float   unused_float   unused_float   ...   unused_string   unused_string   unused_string
    0         0.127          0.1382         0.1422         0.1432   ...                                   2
    1         0.1283         0.1395         0.1435         0.1446   ...                                   2
    2         0.6207         0.6123         0.6131         0.623    ...
    3         0.6201         0.6117         0.6125         0.6224   ...
    4         0.0951         0.1092         0.1116         0.1098   ...                                   8
             ...            ...            ...            ...             ...             ...             ...
11836         0.5931         0.5947         0.5884         0.5848   ...                                   5
11837         0.4401         0.448          0.4456         0.4364   ...
11838         0.4402         0.4482         0.4457         0.4366   ...
11839         0.5481         0.5892         0.2607         0.3144   ...                                   9
11840         0.4082         0.359          0.423          0.2827   ...                                   9

 Name   HISP2           NEWID
 Role   unused_string   unused_string
    0   2               03111041
    1   2               03111042
    2                   03111051
    3                   03111052
    4                   03111061
        ...             ...
11836                   03324112
11837                   03324151
11838                   03324152
11839                   03324161
11840                   03324162


11841 rows x 387 columns
memory usage: 44.89 MB
name: FMLD
type: getml.data.DataFrame
url: http://localhost:1709/#/getdataframe/consumer_expenditures/FMLD/

In [6]:
# -----------------------------------------------------------------------------
# Load MEMD

memd_fnames = [
    RAW_DATA_FOLDER + "memd151.csv",
    RAW_DATA_FOLDER + "memd152.csv",
    RAW_DATA_FOLDER + "memd153.csv",
    RAW_DATA_FOLDER + "memd154.csv"
]

# The sniffer will interpret NEWID
# as a numeric column. But we want it
# to be treated as a string.
memd_roles = {"unused_string": ["NEWID"]}

df_memd = data.DataFrame.from_csv(
    fnames=memd_fnames,
    name="MEMD",
    roles=memd_roles
)

df_memd

 Name        MARITAL       MEMBRACE            SEX            AGE   ...   SEMP_RMM        SOCSRRET        SOCS_RET
 Role   unused_float   unused_float   unused_float   unused_float   ...   unused_string   unused_string   unused_string
    0              1              4              1             66   ...   A               2               D
    1              1              4              2             62   ...   A               2               D
    2              1              4              1             66   ...   A               2               D
    3              1              4              2             62   ...   A               2               D
    4              3              1              1             48   ...   A               2               D
                 ...            ...            ...            ...         ...             ...             ...
28655              4              1              1             50   ...   A               2               D
28656              5              1              1             57   ...   A               2               D
28657              5              1              1             57   ...   A               2               D
28658              2              1              2             69   ...   A               1               D
28659              2              1              2             69   ...   A               1               D

 Name   WKSTATUS        NEWID
 Role   unused_string   unused_string
    0                   03111041
    1                   03111041
    2                   03111042
    3                   03111042
    4   1               03111051
        ...             ...
28655   1               03324112
28656   1               03324151
28657   1               03324152
28658                   03324161
28659                   03324162


28660 rows x 168 columns
memory usage: 48.49 MB
name: MEMD
type: getml.data.DataFrame
url: http://localhost:1709/#/getdataframe/consumer_expenditures/MEMD/

### 1.3 Data exploration

The first thing we want to do is to define the target.

Strangely enough, the "GIFT" column we want to predict is encoded into 1 for gift and 2 for no gift. We want to turn that into a binary column.

In [7]:
target = (df_expd["GIFT"] == 1)

df_expd.add(target, "TARGET", roles.target)

We will also turn the "EXPNMO" column into a numerical value (the CSV sniffer has interpreted it as a string, because of missing values).

In [8]:
df_expd.set_role("EXPNMO", roles.numerical)

### 1.4 Annotating the columns

We now want to annotate the data in EXPD. We have already done so for "EXPNMO" and our target variable, but we want to do the same for other columns as well.

Specifically, we will assign roles and units to the columns. To learn more about roles and units, check out the documentation:

https://docs.getml.com/latest/user_guide/annotating_data/annotating_data.html

In [9]:
# -----------------------------------------------------------------------------
# Make EXPNYR and COST numerical columns

df_expd.set_role(["EXPNYR", "COST"], roles.numerical)

df_expd.set_unit(["EXPNMO"], "month")
df_expd.set_unit(["COST"], "cost")

# -----------------------------------------------------------------------------
# Make newid a join key.

df_expd.set_role("NEWID", roles.join_key)

# -----------------------------------------------------------------------------
# Remove all entries, for which EXPNYR or EXPNYR are nan.

expnyr = df_expd["EXPNYR"]
expnmo = df_expd["EXPNMO"]

not_nan = (expnyr.is_nan() | expnmo.is_nan()).is_false()

df_expd = df_expd[not_nan].to_df("EXPD")

# -----------------------------------------------------------------------------
# Generate time stamps.

expnyr = df_expd["EXPNYR"]
expnmo = df_expd["EXPNMO"]

ts_strings = expnyr.as_str() + "/" + expnmo.as_str()

df_expd["TIME_STAMP"] = ts_strings.as_ts(["%Y/%n"])

df_expd.set_role("TIME_STAMP", roles.time_stamp)

# -----------------------------------------------------------------------------

df_expd.set_role("UCC", roles.categorical)
df_expd.set_unit("UCC", "UCC")

# -----------------------------------------------------------------------------

df_expd

  Name   TIME_STAMP                       NEWID   TARGET   UCC           ...   EXPN_QDY        EXPNWKDY        EXPN_KDY
  Role   time_stamp                    join_key   target   categorical   ...   unused_string   unused_string   unused_string
 Units   time stamp, comparison only                       UCC           ...
     0   2015-01-01                    03111041        0   010210        ...   D               1               D
     1   2015-01-01                    03111041        0   060110        ...   D               1               D
     2   2015-01-01                    03111041        0   060210        ...   D               1               D
     3   2015-01-01                    03111041        0   090110        ...   D               1               D
     4   2015-01-01                    03111041        0   090210        ...   D               1               D
         ...                                ...      ...   ...                 ...             ...             ...
398890   2015-12-01                    03324162        0   550210        ...   D               7               D
398891   2015-12-01                    03324162        0   590230        ...   D               6               D
398892   2015-12-01                    03324162        0   660000        ...   D               6               D
398893   2015-12-01                    03324162        0   660000        ...   D               6               D
398894   2015-12-01                    03324162        0   680110        ...   D               3               D

  Name   EXPNMO_         EXPNYR_
  Role   unused_string   unused_string
 Units
     0   D               D
     1   D               D
     2   D               D
     3   D               D
     4   D               D
         ...             ...
398890   D               D
398891   D               D
398892   D               D
398893   D               D
398894   D               D


398895 rows x 16 columns
memory usage: 52.65 MB
name: EXPD
type: getml.data.DataFrame
url: http://localhost:1709/#/getdataframe/consumer_expenditures/EXPD/

We're done with EXPD. We can now save our work:

In [10]:
df_expd = df_expd.save()

#### 1.4.2 MEMD

Next, we annotate the columns in MEMD. MEMD contains information on each member of the household. We just pick a couple of columns we find interesting and assign them the role categorical or numerical.

Also, we need to tell it that NEWID is our join key.

In [11]:
df_memd.set_role([
    "MARITAL",
    "SEX",
    "EMPLTYPE",
    "OCCULIST",
    "WHYNOWRK",
    "EDUCA",
    "MEDICARE",
    "PAYPERD"], roles.categorical)

df_memd.set_role(["AGE", "WAGEX"], roles.numerical)

df_memd.set_role("NEWID", roles.join_key)

df_memd = df_memd.save()

df_memd

 Name      NEWID   MARITAL       SEX           EMPLTYPE      ...   SEMPFRMM        SEMP_RMM        SOCSRRET
 Role   join_key   categorical   categorical   categorical   ...   unused_string   unused_string   unused_string
    0   03111041   1             1             NULL          ...   .               A               2
    1   03111041   1             2             NULL          ...   .               A               2
    2   03111042   1             1             NULL          ...   .               A               2
    3   03111042   1             2             NULL          ...   .               A               2
    4   03111051   3             1             1             ...   .               A               2
             ...   ...           ...           ...                 ...             ...             ...
28655   03324112   4             1             1             ...   .               A               2
28656   03324151   5             1             1             ...   .               A               2
28657   03324152   5             1             1             ...   .               A               2
28658   03324161   2             2             NULL          ...   .               A               1
28659   03324162   2             2             NULL          ...   .               A               1

 Name   SOCS_RET        WKSTATUS
 Role   unused_string   unused_string
    0   D
    1   D
    2   D
    3   D
    4   D               1
        ...             ...
28655   D               1
28656   D               1
28657   D               1
28658   D
28659   D


28660 rows x 168 columns
memory usage: 46.84 MB
name: MEMD
type: getml.data.DataFrame
url: http://localhost:1709/#/getdataframe/consumer_expenditures/MEMD/

#### 1.4.3 FMLD

In [12]:
income_ranks = [
    "INC_RANK",
    "INC_RNK1",
    "INC_RNK2",
    "INC_RNK3",
    "INC_RNK4",
    "INC_RNK5",
    "INC_RNKM"
]

df_fmld.set_role(income_ranks, roles.numerical)

for inc in income_ranks:
    df_fmld.set_unit(inc, inc)

df_fmld.set_role("NEWID", roles.join_key)

df_fmld

 Name      NEWID    INC_RANK    INC_RNK1    INC_RNK2   ...   INT_PHON        INT__OME        INT__HON        DIVISION
 Role   join_key   numerical   numerical   numerical   ...   unused_string   unused_string   unused_string   unused_string
Units               INC_RANK    INC_RNK1    INC_RNK2   ...
    0   03111041      0.3044      0.1448      0.1427   ...                                                   2
    1   03111042      0.3063      0.1462      0.1444   ...                                                   2
    2   03111051      0.6931      0.6222      0.6204   ...
    3   03111052      0.6926      0.6216      0.6198   ...
    4   03111061      0.2817      0.113       0.1128   ...                                                   8
             ...     ...         ...         ...             ...             ...             ...             ...
11836   03324112      0.6854      0.5958      0.5914   ...                                                   5
11837   03324151      0.5643      0.4463      0.4503   ...
11838   03324152      0.5645      0.4464      0.4505   ...
11839   03324161      0.396       0.6675      0.71     ...                                                   9
11840   03324162      0.3953      0.3791      0.5843   ...                                                   9

 Name   HISP2
 Role   unused_string
Units
    0   2
    1   2
    2
    3
    4
        ...
11836
11837
11838
11839
11840


11841 rows x 387 columns
memory usage: 44.74 MB
name: FMLD
type: getml.data.DataFrame
url: http://localhost:1709/#/getdataframe/consumer_expenditures/FMLD/

#### 1.4.4 POPULATION

Our next step is to create the POPULATION table. The POPULATION table defines the statistical population (hence the name) and contains our target variable.

We want to predict whether an expenditure was purchased as a gift, so EXPD is a good starting point. However, there is also the FMLD table. FMLD contains demographic information on the household as whole. Because this information is unique for every household, EXPD and FMLD are in a many-to-one relationship. We can therefore directly join FMLD onto EXPD and do not have extract any features from FMLD.

To learn more about joining, check out the official documentation:

https://docs.getml.com/latest/api/getml.data.DataFrame.html#getml.data.DataFrame.join

In [13]:
split = getml.data.split.random(train=0.7, validation=0.15, test=0.15)
split

   0   train
   1   validation
   2   train
   3   validation
   4   validation
       ...


infinite number of  rows
type: StringColumnView

## 2. Predictive modeling

Enough with the data preparation. Let's get to the fun part: Extracting the features.

### 2.1 Defining the data model

First, we define the data model.

What we want to do is the following: 

1. We want to compare every expenditure made to all *expenditures by the same household* (EXPD).

2. We want to check out whether *certain kinds of items have been purchased as a gift in the past* (EXPD).

2. We want to aggregate all available information on the *individual members of the household* (MEMD).

In [14]:
star_schema = getml.data.StarSchema(alias="POPULATION", population=df_expd, split=split)

star_schema.join(
    df_expd,
    on="NEWID",
    time_stamps="TIME_STAMP"
)

star_schema.join(
    df_expd,
    on="NEWID",
    time_stamps="TIME_STAMP",
    horizon=getml.data.time.days(1),
    allow_lagged_targets=True,
)

star_schema.join(
    df_fmld,
    on="NEWID",
    relationship=getml.data.relationship.many_to_one,
)

star_schema.join(
    df_memd,
    on="NEWID",
)

star_schema

### 2.2 Setting the hyperparameters

We use `XGBoost` as our predictor and `FastProp` (short for fast propsitionalization) to generate our features. You are free to play with the hyperparameters.

In [ ]:
ucc1 = preprocessors.Substring(0, 1, "UCC")
ucc2 = preprocessors.Substring(0, 2, "UCC")
ucc3 = preprocessors.Substring(0, 3, "UCC")
ucc4 = preprocessors.Substring(0, 4, "UCC")
ucc5 = preprocessors.Substring(0, 5, "UCC")

mapping = preprocessors.Mapping()

fast_prop = feature_learning.FastPropModel(
    loss_function=loss_functions.CrossEntropyLoss,
    num_threads=1,
    sampling_factor=0.1,
)

relboost = feature_learning.RelboostModel(
    loss_function=loss_functions.CrossEntropyLoss,
    num_threads=1,
)

feature_selector = predictors.XGBoostClassifier()

predictor = predictors.XGBoostClassifier(
    booster="gbtree",
    n_estimators=100,
    max_depth=7,
    reg_lambda=0.0,
    n_jobs=1
)

In [ ]:
pipe1 = Pipeline(
    tags=["first shot", "propositionalization"],
    data_model=container.data_model,
    share_selected_features=0.9,
    preprocessors=[ucc1, ucc2, ucc3, ucc4, ucc5, mapping],
    feature_learners=fast_prop,
    feature_selectors=feature_selector,
    predictors=predictor
)

pipe1

In [ ]:
pipe2 = Pipeline(
    tags=["first shot", "relboost"],
    data_model=container.data_model,
    share_selected_features=0.9,
    preprocessors=[ucc1, ucc2, ucc3, ucc4, ucc5, mapping],
    feature_learners=relboost,
    feature_selectors=feature_selector,
    predictors=predictor
)

pipe2

`.fit(...)` will automatically call `.check(...)`, but it is always a good idea to call `.check(...)` separately, so we still have time for some last-minute fixes.

### 2.3 Training the pipeline

OK, let's go:

In [ ]:
pipe1.check(container.train)

In [ ]:
pipe1.fit(container.train)

In [ ]:
pipe2.check(container.train)

In [ ]:
pipe2.fit(container.train)

### 2.4 Evaluating the pipeline

We want to know how well we did. We will to an in-sample and an out-of-sample evaluation:

In [ ]:
pipe1.score(container.test)

In [ ]:
pipe2.score(container.test)

### 2.5 Studying the features

It is very important that we get an idea about the features that the propositionalization algorithm has produced.

In [ ]:
LENGTH=50

names, correlations = pipe1.features.correlations()

plt.subplots(figsize=(20, 10))

plt.bar(names[:LENGTH], correlations[:LENGTH], color='#6829c2')

plt.title("feature correlations")
plt.grid(True)
plt.xlabel("features")
plt.ylabel("correlations")
plt.xticks(rotation='vertical')

plt.show()

In [ ]:
LENGTH=50

names, correlations = pipe2.features.correlations()

plt.subplots(figsize=(20, 10))

plt.bar(names[:LENGTH], correlations[:LENGTH], color='#6829c2')

plt.title("feature correlations")
plt.grid(True)
plt.xlabel("features")
plt.ylabel("correlations")
plt.xticks(rotation='vertical')

plt.show()

We can express the features in SQLite3:

Because getML uses a feature learning approach, the concept of feature importances can also be carried over to the individual columns.

In [ ]:
names, importances = pipe1.columns.importances()

plt.subplots(figsize=(20, 10))

plt.bar(names, importances, color='#6829c2')

plt.title("column importances")
plt.grid(True)
plt.xlabel("columns")
plt.ylabel("importance")
plt.xticks(rotation='vertical')

plt.show()

In [ ]:
names, importances = pipe2.columns.importances()

plt.subplots(figsize=(20, 10))

plt.bar(names, importances, color='#6829c2')

plt.title("column importances")
plt.grid(True)
plt.xlabel("columns")
plt.ylabel("importance")
plt.xticks(rotation='vertical')

plt.show()

## 3. Conclusion

In this notebook, we have shown how you can use relational learning to predict whether items were purchased as a gift. We did this to highlight the importance of relational learning. Relational learning can be used in many real-world data science applications, but unfortunately most data scientists don't even know what relation learning is.

If you want to learn more about getML, check out the [documentation](https://getml.com/product).

# Next Steps
This tutorial went through the basics of applying getML to a moderately-sized retail data set. 

If you are interested in further real-world applications of getML, head back to the [notebook overview](welcome.md) and choose one of the remaining examples.

Here is some additional material from our [documentation](https://docs.getml.com/latest/) if you want to learn more about getML:
* [Feature learning with Multirel](https://docs.getml.com/latest/user_guide/feature_engineering/feature_engineering.html#multirel)
* [Feature learning with Relboost](https://docs.getml.com/latest/user_guide/feature_engineering/feature_engineering.html#relboost)

# Get in contact

If you have any question schedule a [call with Alex](https://go.getml.com/meetings/alexander-uhlig/getml-demo), the co-founder of getML, or write us an [email](team@getml.com). Prefer a private demo of getML? Just contact us to make an appointment.